apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-surveillance
  annotations:
    github.com/project-slug: amvirdev/github-surveillance
spec:
  type: other
  lifecycle: unknown
  owner: amvirdev
