apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: github-surveillance-components
  description: Collection of all GitHub Surveillance components
  annotations:
    github.com/project-slug: enginuity-io/github-surveillance
    backstage.io/managed-by-origin-location: url:https://github.com/enginuity-io/github-surveillance
spec:
  targets:
    # Frontend components
    - ./catalog-info-frontend.yaml
    # Backend components
    - ./catalog-info-backend.yaml
